import logging
from typing import Dict, List

import requests
from github import Auth, Github

from .config import settings

logger = logging.getLogger(__name__)


class GitHubPRClient:
    """GitHub client for PR operations using PyGithub."""

    def __init__(self) -> None:
        auth = Auth.Token(settings.github_token)
        self.client = Github(auth=auth)
        self.repo = self.client.get_repo(settings.github_repository)

    def get_pr_data(self, pr_number: int) -> Dict:
        pr = self.repo.get_pull(pr_number)

        files: List[Dict] = [
            {
                "filename": f.filename,
                "additions": f.additions,
                "deletions": f.deletions,
                "status": f.status,
            }
            for f in pr.get_files()
        ]

        diff_response = requests.get(
            pr.diff_url,
            headers={"Authorization": f"token {settings.github_token}"},
            timeout=30,
        )
        diff_response.raise_for_status()

        return {
            "pr": pr,
            "title": pr.title,
            "body": pr.body,
            "number": pr.number,
            "author": pr.user.login,
            "labels": [l.name for l in pr.labels],
            "files": files,
            "diff": diff_response.text,
        }

    def post_summary_comment(self, pr_number: int, summary: str) -> None:
        pr = self.repo.get_pull(pr_number)

        comment = (
            "## 🤖 Copilot-Powered PR Analysis\n\n"
            f"{summary}\n\n"
            "---\n"
            "*Generated by GitHub Copilot SDK • Automated Code Review*"
        )

        pr.create_issue_comment(comment)
        logger.info("Posted Copilot summary to PR #%s", pr_number)